name: Python package

on:
  push:
    branches:
      - '*'
  workflow_call: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff linter
        run: ruff check --output-format=github src/
      - name: Run ruff formatter check
        run: ruff format --check src/

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ["3.10","3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: oceanum-io/oceanum-python
          ref: prax-cli
          path: libs/oceanum-python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package and dependencies
        run: |
          pip install libs/oceanum-python
          pip install .[test]
      - name: Run unit-tests with parallel execution
        run: |
          pytest --cov oceanum.cli.prax tests/ -n auto -v
