name: Python package

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      
      - name: Install package and dependencies
        run: pip install .[test]
      - name: Lint code with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github --target-version=py310 --exclude=tests
        continue-on-error: true
      - name: Run unit-tests
        run: |
          pytest --cov oceanum-prax
      